name: 'Pytest Evaluator'
description: 'Run Pytest on project and return the results formatted'
inputs:
  pr_author_username:
    description: 'Pull Request author username'
    required: true
outputs:
  result:
    description: 'Evaluation JSON results in base64 format.'
runs:
  using: 'docker'
  image: 'Dockerfile'
