name: 'Pytest Evaluator'
description: 'Run Pytest on project and return the results formatted'
inputs:
  pr_author_username:
    description: 'Pull Request author username'
    required: true
outputs:
  result:
    description: 'Evaluation JSON results in base64 format.'
    value: ${{ steps.run_pytest.outputs.result }}

runs:
  using: 'composite'
  steps:
    - id: run_pytest
      shell: bash
      run: ${{ github.action_path }}/evaluate.sh
      env:
        EVALUATOR_REQUIREMENTS: ${{ github.action_path }}/requirements.txt
        EVALUATOR_SRC: ${{ github.action_path }}/src
        INPUT_PR_AUTHOR_USERNAME: ${{ inputs.pr_author_username }}
        GITHUB_REPOSITORY: ${{ github.repository }}
