name: 'Pytest Evaluator'
description: 'Run Pytest on project and return the results formatted'
inputs:
  repository_main_branch:
    description: 'GitHub main branch to get the original tests and requirements.'
    default: 'master'
    required: true
outputs:
  result:
    description: 'Evaluation JSON results in base64 format.'
runs:
  using: 'docker'
  image: 'Dockerfile'
