on:
  pull_request:
    types: [opened, synchronize]

jobs:
  py_job:
    name: Python CI
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        python3 -m flake8 --append-config=setup.cfg
    - name: Test with pytest
      run: |
        python -m pytest
